### ISSUE TITLE
Mainpage – Vorschautext Position

### ISSUE THREAD

**Issue by belameiers** [whatstodo/whatstodo#10]
- Hover Text -> cursor: pointer;
- Hinweis auf mehr am Ende des Vorschautextes
- Hover Position Titel (aktuell ausgeklappter Position) -> cursor: default;
- Ausklapper nur schließen durch das ausklappen einer anderen Position?
- Ausklapper nicht schließen wenn die aktuell ausgeklappte Position über die checkbox auswählt.
- Bei click auf whatstodo.design ausgeklappte Position einklappen

**Comment by arnoson** [comment]
`Bei click auf whatstodo.design ausgeklappte Position einklappen` das ist leider nicht ganz so einfach, weil vue kein event feuert wenn man die selbe Seite nochmal anklickt
